version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_NAME=blog
      - DB_USER=root
      - DB_PASSWORD=yourpassword
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: blog
    volumes:
      - db_data:/var/lib/mysql
      - ./blog_database.sql:/docker-entrypoint-initdb.d/blog_database.sql

volumes:
  db_data: