name: Docker CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/firozasif_blogpost:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/firozasif_blogpost:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build_and_publish
  #   steps:
  #     - name: Deploy application
  #       run: |
  #         # Example: deploy to DigitalOcean or another cloud provider
  #         echo "Deploying to server..."
